Build:
	g++ -c sorted_array.cc
	g++ -c sorted_array_main.cc
	g++ -o sorted_array sorted_array.o sorted_array_main.o
	g++ -c integer_set.cc
	g++ -c integer_set_main.cc
	g++ -o integer_set integer_set.o integer_set_main.o
clean:
	rm sorted_array.o sorted_array_main.o sorted_array integer_set.o integer_set_main.o integer_set
