Build:
	g++ -c print_shape.cc
	g++ -c print_shape_main.cc
	g++ -o print_shape print_shape.o print_shape_main.o
	g++ -o clock_time clock_time.cc clocks.cc clocks_main.cc
clean:
	rm print_shape print_shape.o print_shape_main.o clock_time
