Build:
	g++ -c simple_shape.cc
	g++ -c simple_shape_main.cc
	g++ -o simple_shape simple_shape.o simple_shape_main.o
	g++ -c simple_account.cc
	g++ -c simple_account_main.cc
	g++ -o simple_account simple_account.o simple_account_main.o
clean:
	rm -rf simple_shape simple_account simple_shape.o simple_shape_main.o simple_account.o simple_account_main.o
