Build:
	g++ -c classes.cc
	g++ -c classes_main.cc
	g++ -o classes classes.o classes_main.o
	g++ -c print_info.cc
	g++ -c print_info_main.cc
	g++ -o print_info print_info.o print_info_main.o
	g++ -c print_member.cc
	g++ -c print_member_main.cc
	g++ -o print_member print_member.o print_member_main.o
clean:
	rm classes classes.o classes_main.o print_info print_info.o print_info_main.o print_member print_member.o print_member_main.o
