Build:
	g++ -o class_function class_function.cc class_function_main.cc
	g++ -o cast_quiz cast_quiz.cc
	g++ -o dynamic_cast dynamic_cast.cc dynamic_cast_main.cc
	g++ -o shapes shapes.cc shapes_main.cc
clean:
	rm class_function cast_quiz dynamic_cast shapes
