Build:
	g++ -c number.cc
	g++ -c number_main.cc
	g++ -o number number.o number_main.o
	g++ -c rectangle.cc
	g++ -c rectangle_main.cc
	g++ -o rectangle rectangle.o rectangle_main.o
clean:
	rm number rectangle number.o number_main.o rectangle.o rectangle_main.o
