Build: 
	g++ -o swaping swaping.cc
	g++ -o command_argument command_argument.cc
	g++ -c circle_main.cc
	g++ -c circle.cc
	g++ -o circle_main circle_main.o circle.o
	g++ -o cmdarg cmdarg.cc
clean:
	rm -rf swaping command_argument circle_main cmdarg
