Build:
	g++ -c Animals.cc
	g++ -c Animals_main.cc
	g++ -o Animals Animals.o Animals_main.o
	g++ -c draw_shape.cc
	g++ -c draw_shape_main.cc
	g++ -o draw_shape draw_shape.o draw_shape_main.o
clean:
	rm Animals Animals.o Animals_main.o draw_shape draw_shape.o draw_shape_main.o
