Bulid:
	g++ -o exception_handling exception_handling.cc
	g++ -o exception_handling2 exception_handling2.cc
	g++ -o exception_handling3 exception_handling3.cc
	g++ -o exception_handling4 exception_handling4.cc
clean:
	rm exception_handling exception_handling2 exception_handling3 exception_handling4
